name: Standards Check

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - 'dependabot/**'

jobs:
  run-checks:
    runs-on: ubuntu-2g-1cpu-arm64

    steps:
      - uses: uphold/standards-check-action@v1
